################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= vector_addition 
# Cuda source files (compiled with cudacc)
CUFILES		:= vector_addition.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= vector_addition_gold.cpp 

################################################################################
# Rules and targets

include ../../common/common.mk
